project 'Sport Riot.xcodeproj'

# Uncomment the next line to define a global platform for your project          platform :ios, '12.0'

target 'Sport Riot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  # Pods for Sport Riot

  target 'Sport RiotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sport RiotUITests' do
    # Pods for testing
  end

end
